// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttavrofrfgdyccvwxzwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0YXZyb2ZyZmdkeWNjdnd4endiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTA2MjcsImV4cCI6MjA2OTI2NjYyN30.kAGQW2jI9CRInEue2hRalFK7-UjglEUH8nY0GBu87AM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});